version: '3.8'

services:

  redis:
    image: redis:7-alpine
    container_name: go-redis
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - go-network

networks:
  go-network:
    driver: bridge
