basePath: /
definitions:
  models.Task:
    properties:
      attempts:
        type: integer
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      status:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для управления задачами с использованием Redis и SQLite
  title: Task Service API
  version: "1.0"
paths:
  /task:
    post:
      consumes:
      - application/json
      description: Создает новую задачу и помещает в очередь Redis
      parameters:
      - description: Данные задачи
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Создать новую задачу
      tags:
      - tasks
  /task/{id}:
    get:
      description: Возвращает задачу из базы данных по её ID
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Получить задачу по ID
      tags:
      - tasks
swagger: "2.0"
